/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvSeriesRouteImport } from './routes/tv-series'
import { Route as TopListsRouteImport } from './routes/top-lists'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as GamesRouteImport } from './routes/games'
import { Route as EmulatorsRouteImport } from './routes/emulators'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TvSeriesRoute = TvSeriesRouteImport.update({
  id: '/tv-series',
  path: '/tv-series',
  getParentRoute: () => rootRouteImport,
} as any)
const TopListsRoute = TopListsRouteImport.update({
  id: '/top-lists',
  path: '/top-lists',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EmulatorsRoute = EmulatorsRouteImport.update({
  id: '/emulators',
  path: '/emulators',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/emulators': typeof EmulatorsRoute
  '/games': typeof GamesRoute
  '/guides': typeof GuidesRoute
  '/movies': typeof MoviesRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-lists': typeof TopListsRoute
  '/tv-series': typeof TvSeriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/emulators': typeof EmulatorsRoute
  '/games': typeof GamesRoute
  '/guides': typeof GuidesRoute
  '/movies': typeof MoviesRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-lists': typeof TopListsRoute
  '/tv-series': typeof TvSeriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/emulators': typeof EmulatorsRoute
  '/games': typeof GamesRoute
  '/guides': typeof GuidesRoute
  '/movies': typeof MoviesRoute
  '/news': typeof NewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/top-lists': typeof TopListsRoute
  '/tv-series': typeof TvSeriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/apps'
    | '/contact'
    | '/emulators'
    | '/games'
    | '/guides'
    | '/movies'
    | '/news'
    | '/sitemap.xml'
    | '/top-lists'
    | '/tv-series'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/apps'
    | '/contact'
    | '/emulators'
    | '/games'
    | '/guides'
    | '/movies'
    | '/news'
    | '/sitemap.xml'
    | '/top-lists'
    | '/tv-series'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/apps'
    | '/contact'
    | '/emulators'
    | '/games'
    | '/guides'
    | '/movies'
    | '/news'
    | '/sitemap.xml'
    | '/top-lists'
    | '/tv-series'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppsRoute: typeof AppsRoute
  ContactRoute: typeof ContactRoute
  EmulatorsRoute: typeof EmulatorsRoute
  GamesRoute: typeof GamesRoute
  GuidesRoute: typeof GuidesRoute
  MoviesRoute: typeof MoviesRoute
  NewsRoute: typeof NewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopListsRoute: typeof TopListsRoute
  TvSeriesRoute: typeof TvSeriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv-series': {
      id: '/tv-series'
      path: '/tv-series'
      fullPath: '/tv-series'
      preLoaderRoute: typeof TvSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-lists': {
      id: '/top-lists'
      path: '/top-lists'
      fullPath: '/top-lists'
      preLoaderRoute: typeof TopListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emulators': {
      id: '/emulators'
      path: '/emulators'
      fullPath: '/emulators'
      preLoaderRoute: typeof EmulatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppsRoute: AppsRoute,
  ContactRoute: ContactRoute,
  EmulatorsRoute: EmulatorsRoute,
  GamesRoute: GamesRoute,
  GuidesRoute: GuidesRoute,
  MoviesRoute: MoviesRoute,
  NewsRoute: NewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopListsRoute: TopListsRoute,
  TvSeriesRoute: TvSeriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
